package docscontract

import "testing"

func TestWFLOW008RunLocalMaterializationContractIsDocumentedAndBounded(t *testing.T) {
	cases := map[string][]string{
		"skills/kkachi-workflow-trigger/SKILL.md": {
			"WFLOW-008 run-local mode",
			"--route-result <workflow-route-json>",
			"--custom-workflow-packet <workflow-create-dry-run.json>",
			"--approval dry-run:sha256:<hash>",
			"--materialize-run-local",
			"--workflow-file",
			".kkachi/runs/<run_id>/workflow/",
			"materialization.json",
			"workflow.yaml",
			"node-contracts.json",
			"route-result.json",
			"custom-workflow-packet.json",
			"checksums.json",
			"blocked_missing_kah_workflow_capability",
			"before writes",
			"persistent_promotion:false",
			"no_promotion:true",
			"direct_kah_state_write:false",
			"completion_authority:kah_only",
			"fallback_policy:none_fail_closed",
			".kkachi-workflow.yaml",
			".kkachi/workflow-catalog.yaml",
			".kkachi/workflows/*",
			"WFLOW-009",
		},
		"docs/sot/kas-cli-contract.md": {
			"WFLOW-008",
			"workflow-trigger --project <path> --route-result <workflow-route-json> --materialize-run-local --run <run-id> --json",
			"workflow-trigger --project <path> --run <run-id> --custom-workflow-packet <workflow-create-dry-run.json> --approval dry-run:sha256:<hash> --materialize-run-local --json",
			"WFLOW-004 canonical approval semantics",
			"`workflow` command group",
			"blocked_missing_kah_workflow_capability",
			".kkachi/runs/<run_id>/workflow/materialization.json",
			".kkachi/runs/<run_id>/workflow/workflow.yaml",
			".kkachi/runs/<run_id>/workflow/node-contracts.json",
			".kkachi/runs/<run_id>/workflow/route-result.json",
			".kkachi/runs/<run_id>/workflow/custom-workflow-packet.json",
			".kkachi/runs/<run_id>/workflow/checksums.json",
			"kas-node-contracts/v1",
			"approval hash and source packet checksum",
			"`workflow_file`",
			"`completion_authority:kah_only`",
			"`fallback_policy:none_fail_closed`",
			"`direct_kah_state_write:false`",
			"WFLOW-009 promotion/apply",
		},
		"docs/sot/task-dag-workflow-contract.md": {
			"WFLOW-008 implements run-local materialization",
			"--route-result <workflow-route-json>",
			"--custom-workflow-packet <workflow-create-dry-run.json>",
			"--approval",
			"--materialize-run-local",
			"does not reroute raw task metadata",
			"WFLOW-004 canonical approval semantics",
			"KAS preflights effective KAH workflow",
			"capability before non-dry-run materialization",
			".kkachi/runs/<run_id>/workflow/materialization.json",
			".kkachi/runs/<run_id>/workflow/workflow.yaml",
			".kkachi/runs/<run_id>/workflow/node-contracts.json",
			".kkachi/runs/<run_id>/workflow/route-result.json",
			".kkachi/runs/<run_id>/workflow/custom-workflow-packet.json",
			".kkachi/runs/<run_id>/workflow/checksums.json",
			"persistent_promotion:false",
			"`--workflow-file`",
			".kkachi/workflows/<workflow-id>.yaml",
			".kkachi/workflow-catalog.yaml",
			".kkachi-workflow.yaml",
			"WFLOW-009",
		},
		"docs/roadmap.md": {
			"| WFLOW-008 | Implement run-local ephemeral workflow materialization and trigger support | Completed |",
			"run-20260616T105614Z-4b0ebe11b67d",
			"route-result",
			"approved custom packet",
			"preflights installed KAH before writes",
			"`.kkachi/runs/<run_id>/workflow/`",
			"explicit `--workflow-file`",
			"WFLOW-004 approval hashes",
			"official KAB GLM Octo accepted",
			"No `.kkachi-workflow.yaml`, `.kkachi/workflow-catalog.yaml`, or `.kkachi/workflows/*` auto-write",
			"WFLOW-009 promotion/apply remains deferred",
		},
	}
	for rel, needles := range cases {
		requireContainsAll(t, rel, needles)
	}
}
