package docscontract

import "testing"

func TestWFLOW009PromotionContractIsDocumentedAndBounded(t *testing.T) {
	cases := map[string][]string{
		"skills/kkachi-workflow-promote/SKILL.md": {
			"WFLOW-008 run-local workflow",
			"workflow-promote",
			"--target-workflow-id <id>",
			"--reuse-reason <reason>",
			"--dry-run",
			"--apply dry-run:sha256:<hash>",
			"materialization.json",
			"workflow.yaml",
			"node-contracts.json",
			"checksums.json",
			"kas-workflow-promote-packet/v1",
			"source run/materialization provenance",
			"no-write evidence",
			"DAGSM-006",
			".kkachi/workflows/*",
			".kkachi/workflow-catalog.yaml",
			".kkachi-workflow.yaml",
			"KAB state",
			"direct_kah_state_write:false",
			"completion_authority:kah_only",
			"fallback_policy:none_fail_closed",
			"must not be folded into `workflow-trigger`",
		},
		"docs/sot/kas-cli-contract.md": {
			"WFLOW-009",
			"workflow-promote --project <path> --run <run-id> --target-workflow-id <id> --reuse-reason <reason> [--thin-trigger] --dry-run --json",
			"workflow-promote --project <path> --run <run-id> --target-workflow-id <id> --reuse-reason <reason> [--thin-trigger] --apply dry-run:sha256:<hash> --json",
			"must not overload `workflow-trigger`",
			"`--target-workflow-id` and `--reuse-reason` are required",
			"mutually exclusive",
			"`kas-workflow-promote-packet/v1`",
			"source run/materialization provenance",
			"source checksums",
			"target project-local paths",
			"optional thin trigger content",
			"deterministic approval hash",
			"blocked_missing_kah_workflow_catalog_capability",
			"workflow_promote_apply_refused",
			".kkachi/workflows/*",
			".kkachi/workflow-catalog.yaml",
			".kkachi-workflow.yaml",
			"profile files",
			"KAB state",
			"auth/token/provider/gateway/model config",
			"`direct_kah_state_write:false`",
			"`completion_authority:kah_only`",
			"`fallback_policy:none_fail_closed`",
		},
		"docs/sot/task-dag-workflow-contract.md": {
			"WFLOW-009 implements explicit promotion proposal",
			"not by overloading `workflow-trigger`",
			"workflow-promote --project <path> --run <run-id> --target-workflow-id <id> --reuse-reason <reason> [--thin-trigger] --dry-run --json",
			"workflow-promote --project <path> --run <run-id> --target-workflow-id <id> --reuse-reason <reason> [--thin-trigger] --apply dry-run:sha256:<hash> --json",
			"materialization.json",
			"workflow.yaml",
			"node-contracts.json",
			"checksums.json",
			"`--target-workflow-id` and",
			"`--reuse-reason` are required",
			"mutually exclusive",
			"`kas-workflow-promote-packet/v1`",
			"source materialization provenance",
			"source checksums",
			"no-write evidence",
			"Until DAGSM-006 reviewed",
			"correct-hash apply remains",
			".kkachi/workflows/*",
			".kkachi/workflow-catalog.yaml",
			".kkachi-workflow.yaml",
			"KAB state",
			"fallback backend selection",
			"`direct_kah_state_write:false`",
			"`completion_authority:kah_only`",
			"`fallback_policy:none_fail_closed`",
		},
		"README.md": {
			"workflow-promote --project <path> --run <run-id> --target-workflow-id <id> --reuse-reason <reason> [--thin-trigger] --dry-run",
			"workflow-promote --project <path> --run <run-id> --target-workflow-id <id> --reuse-reason <reason> [--thin-trigger] --apply dry-run:sha256:<hash>",
			"WFLOW-009",
			"existing WFLOW-008 run-local materialization bundle",
			"`kas-workflow-promote-packet/v1`",
			"source provenance/checksums",
			"no-write evidence",
			"fail-closed while reviewed DAGSM-006 catalog",
			".kkachi/workflows/*",
			".kkachi/workflow-catalog.yaml",
			".kkachi-workflow.yaml",
			"KAB state",
			"fallback backend selection",
		},
		"skill-pack.yaml": {
			"kkachi-workflow-promote",
		},
	}
	for rel, needles := range cases {
		requireContainsAll(t, rel, needles)
	}
}
